[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --include=dev",
  "cd client && npm install --include=dev",
  "cd server && npm install --include=dev"
]

[phases.build]
cmds = [
  "cd client && npm run build",
  "cd server && npm run build"
]

[start]
cmd = "cd server && npm start"

[variables]
NODE_ENV = "production"
PORT = "5000"